const colors = {
  light: {
    text: '#0A1628',
    tint: '#0054A6',
    background: '#FFFFFF',
    foreground: '#0A1628',
    card: '#FFFFFF',
    cardForeground: '#0A1628',
    primary: '#0054A6',
    primaryForeground: '#FFFFFF',
    primaryLight: '#E8F2FF',
    secondary: '#F0F7FF',
    secondaryForeground: '#0054A6',
    muted: '#F4F8FF',
    mutedForeground: '#6B8AAA',
    accent: '#00B4D8',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#E2EBF5',
    input: '#E2EBF5',
    success: '#22C55E',
    successLight: '#F0FDF4',
    warning: '#F59E0B',
    warningLight: '#FFFBEB',
    surface: '#F7FAFF',
  },
  dark: {
    text: '#EAEEF5',
    tint: '#4A9EE8',
    background: '#060E1B',
    foreground: '#EAEEF5',
    card: '#132035',
    cardForeground: '#EAEEF5',
    primary: '#2B7FE8',
    primaryForeground: '#FFFFFF',
    primaryLight: '#0D2A50',
    secondary: '#0D1A2E',
    secondaryForeground: '#A0BCD8',
    muted: '#0D1A2E',
    mutedForeground: '#6B8AAA',
    accent: '#00C2CB',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#1E3050',
    input: '#1E3050',
    success: '#22C55E',
    successLight: '#052E16',
    warning: '#F59E0B',
    warningLight: '#292200',
    surface: '#0D1A2E',
  },
  radius: 12,
};

export default colors;
